name: Docker

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Extract branch name
        shell: bash
        run: |
          tag=${GITHUB_REF#refs/tags/}
          tag=${tag#refs/heads/}
          if echo $tag | grep -q -E "[0-9]+\.[0-9]+\.[0-9]+"; then
            tag="v$tag"
          fi
          echo "##[set-output name=tag;]$tag"
        id: extract_branch

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push docker
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: leishi1313/downloader-exporter:latest,leishi1313/downloader-exporter:${{ steps.extract_branch.outputs.tag }}
